apiVersion: v1
kind: Service
metadata:
  name: simple-app
  labels:
    app: simple-app
    prometheus-monitored: "true"
spec:
  selector:
    app: simple-app
  ports:
    - name: http
      port: 8080
      targetPort: 8080
    - name: metrics
      port: 9113
      targetPort: 9113
  type: ClusterIP
